version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "rm -rf tmp/pids/server.pid &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/:cached
    tty: true
    stdin_open: true
