version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "rm -rf tmp/pids/server.pid &&
      bundle exec puma -C config/puma.rb"
    volumes:
      - .:/usr/src/app/:cached
      # nginx から sockets を扱えるようにマウントする
      - web-sockets-data:/usr/src/app/tmp/sockets
    tty: true
    stdin_open: true
  nginx:
    build:
      # 起点をルートディレクトリにする
      # https://qiita.com/sam8helloworld/items/e7fffa9afc82aea68a7a
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      # マウントされた sockets を扱う
      - web-sockets-data:/usr/src/app/tmp/sockets
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  web-sockets-data:
